---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/bybit_listener/
    - mkdir -p $DEPLOYPATH
    - rsync -avz . $DEPLOYPATH --exclude '.git' --exclude '.env' --exclude '__pycache__'
    - cd $DEPLOYPATH
    - python3 -m venv env
    - source env/bin/activate
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
    - chmod +x start_listener.sh
    - ./start_listener.sh
