deployment:
  tasks:
    # Set the deployment path to the app folder
    - export DEPLOYPATH=/home/osgawcom/ichhaberecht.com/app

    # Create the deployment directory if it doesn't exist
    - echo "Creating deployment directory at $DEPLOYPATH"
    - mkdir -p $DEPLOYPATH

    # Sync files from the Git repo to the app folder, excluding unnecessary files
    - echo "Syncing files to $DEPLOYPATH"
    - rsync -avz . $DEPLOYPATH --exclude '.git' --exclude '.env' --exclude '__pycache__'
