---
deployment:
  tasks:
    - export DEPLOYPATH=$GIT_WORK_TREE  # Automatically uses the path defined in cPanel Git settings
    - mkdir -p $DEPLOYPATH
    - rsync -avz . $DEPLOYPATH --exclude '.git' --exclude '.env' --exclude '__pycache__'
    - cd $DEPLOYPATH
    - chmod +x setup.sh
    - ./setup.sh >> deployment_log.log 2>> deployment_errors.log
