---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/osgawcom/ichhaberecht.com/bybit_stream_data
      - mkdir -p $DEPLOYPATH
      - rsync -avz . $DEPLOYPATH --exclude '.git' --exclude '.env' --exclude '__pycache__'
      - cd $DEPLOYPATH
      - chmod +x setup.sh
      - ./setup.sh >> deployment_log.log 2>> deployment_errors.log
  