# === config.yaml ===
# bybit_listener/config.yaml

websocket_url: "wss://stream.bybit.com/realtime"

parquet_storage_path: "./parquet_data/"

# Timezone for daily rollover (e.g., UTC, your local timezone)
timezone: "UTC"

# Scheduling time for saving data (HH:MM in 24-hour format)
save_time: "00:00"

# Log file path
log_file: "./logs/listener.log"

# Path to trigger file for on-demand saving
trigger_file_path: "./save_now.trigger"
