# config.yaml

# Logging Settings
log_file: "./logs/listener.log"

# Trigger Settings
trigger_file: "./save_now.trigger"  # Path to the trigger file for on-demand saving

# Scheduling Settings
save_time_utc: "00:00"  # Time to trigger daily save in UTC (HH:MM format)
